# You can set multiple versions of node here
language: node_js
node_js:
  - 11.6.0

# This tells Travis to cache the node_modules files
cache: npm

# Travis lifecycle methods
before_install:
  - echo "before_install my changes"
install:
  - echo "install my changes"
before_script:
  - echo "before_script my changes"
script:
  - echo "script my changes"
after_success:
  - echo "after_success my changes"
after_failure:
  - echo "after_failure my changes"
after_script:
  - echo "after_script my changes"
